global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: payment-svc
    static_configs:
      - targets: ['payment-svc:8001']
        labels:
          service: payment-svc
          team: payments

  - job_name: auth-svc
    static_configs:
      - targets: ['auth-svc:8002']
        labels:
          service: auth-svc
          team: identity

  - job_name: loan-svc
    static_configs:
      - targets: ['loan-svc:8003']
        labels:
          service: loan-svc
          team: lending

  - job_name: notification-svc
    static_configs:
      - targets: ['notification-svc:8004']
        labels:
          service: notification-svc
          team: communications